%{
    open Tpscrpt
%}

%token <int> T_INT_LIT
%token <string> T_STR_LIT
%token <string> T_IDENTIFIER
%token T_NUMBER T_STRING T_BOOLEAN T_IF T_ELSE T_WHILE T_RETURN T_LET T_VAR T_FUNCTION
%token T_OPEN_PAR T_CLOSE_PAR T_OPEN_BRA T_CLOSE_BRA T_OPEN_SQR T_CLOSE_SQR
%token T_PLUS T_MINUS T_MUL T_DIV T_MOD T_EQ T_NEQ T_LT T_GT T_LE T_GE T_AND T_OR T_NOT T_POW
%token EOL EOF